<?php

use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\View;

?>

<?= view('components/breadcrumbs', ['links' => $breadcrumbs]) ?>

<div id="reminder-admin-config">

    <h1><?= $title ?></h1>

    <div id="reminder-admin-config-content">

        <h3><?= I18N::translate('Cron settings') ?></h3>

        <div>
            <p><?= I18N::translate('Module require configured Cron entry for work') ?>.</p>
            <p><?= I18N::translate('You only need to add the following Cron entry to your server') ?>:</p>

            <div class="input-group mb-3">
                <input type="text" class="form-control" id="reminder-admin-config-cron-input">
                <div class="input-group-append">
                    <span class="input-group-text" id="reminder-admin-config-cron-text"></span>
                </div>
            </div>
        </div>

        <hr>

        <h3><?= I18N::translate('Events settings') ?></h3>

        <div>
            <p><?= I18N::translate('Which type of events will be reminded') ?></p>

            <form method="post" id="settings-form" action="<?= e($routes['events']) ?>">
                <?= csrf_field() ?>

                <div class="input-group">
                    <?= view('components/select', [
                        'name' => 'events[]',
                        'id' => 'reminder-events',
                        'selected' => $eventsSelected,
                        'options' => $eventsOptions,
                        'class' => 'tom-select',
                        'multiple' => true,
                    ]) ?>
                    <button type="submit" class="btn btn-secondary">
                        <?= I18N::translate('Save') ?>
                    </button>
                </div>
            </form>
        </div>

        <hr>

        <h3><?= I18N::translate('User settings') ?></h3>

        <table id="reminder-admin-config-table" class="table" data-url="<?= e($routes['data']) ?>">
            <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>E-mail</th>
                <th class="text-right">Reminders</th>
            </tr>
            </thead>
            <tbody></tbody>
        </table>

    </div>

</div>

<?php View::push('javascript') ?>
<script type="application/javascript">
    window.WT_REMINDER = JSON.parse(decodeURIComponent("<?= rawurlencode(json_encode([ 'routes' => $routes ])) ?>"))
</script>
<?php foreach ($scripts as $path) : ?>
    <script type="text/javascript" src="<?= $path ?>"></script>
<?php endforeach ?>
<?php View::endpush() ?>

<?php View::push('styles') ?>
<?php foreach ($styles as $path) : ?>
    <link rel="stylesheet" href="<?= $path ?>">
<?php endforeach ?>
<?php View::endpush() ?>
